In [1]:
import pandas as pd                         # Import Pandas library
import numpy as np                          # Import NumPy library
import matplotlib.pyplot as plt             # Import Matplotlib library
%matplotlib inline
from google.colab import files
uploaded = files.upload()

Saving bill_authentication.csv to bill_authentication.csv

In [2]:
import io
bankdata = pd.read_csv(io.BytesIO(uploaded["bill_authentication.csv"]))  # Reads uploaded excel File
bankdata                                                                 # Displays the loaded data in notebook

      Variance  Skewness  Curtosis  Entropy  Class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [3]:
bankdata.shape                # Displays number of rows and columns

(1372, 5)

In [4]:
bankdata.head()               # Displays first 5 rows

   Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [5]:
# Split the data into attributes/features and labels/target
X = bankdata.drop('Class', axis=1)                            # Drop Class from dataframe
y = bankdata['Class']
y

0       0
1       0
2       0
3       0
4       0
       ..
1367    1
1368    1
1369    1
1370    1
1371    1
Name: Class, Length: 1372, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)         # 75% training and 25% testing
X_train

      Variance  Skewness   Curtosis   Entropy
999   -4.73310  -6.17890  11.388000 -1.074100
1366  -2.41000   3.74330  -0.402150 -1.295300
187    1.83140   6.36720  -0.036278  0.049554
548    1.85330   6.14580   1.017600 -2.040100
897   -0.28696   3.17840  -3.576700 -3.189600
...        ...       ...        ...       ...
1129  -0.40951  -0.15521   0.060545 -0.088807
877   -5.12160  -5.31180  10.384600 -1.061200
148    3.62770   0.98290   0.688610  0.634030
1259  -1.83870  -6.30100   5.650600  0.195670
139   -0.20620   9.22070  -3.704400 -6.810300

[1029 rows x 4 columns]

from matplotlib import pyplot as plt
X_train['Variance'].plot(kind='hist', bins=20, title='Variance')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_train['Skewness'].plot(kind='hist', bins=20, title='Skewness')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_train['Curtosis'].plot(kind='hist', bins=20, title='Curtosis')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_train['Entropy'].plot(kind='hist', bins=20, title='Entropy')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_train.plot(kind='scatter', x='Variance', y='Skewness', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_train.plot(kind='scatter', x='Skewness', y='Curtosis', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_train.plot(kind='scatter', x='Curtosis', y='Entropy', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_train['Variance'].plot(kind='line', figsize=(8, 4), title='Variance')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
X_train['Skewness'].plot(kind='line', figsize=(8, 4), title='Skewness')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
X_train['Curtosis'].plot(kind='line', figsize=(8, 4), title='Curtosis')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
X_train['Entropy'].plot(kind='line', figsize=(8, 4), title='Entropy')
plt.gca().spines[['top', 'right']].set_visible(False)

In [8]:
from sklearn.svm import SVC                  # Imports the Support Vector Classification class from scikit-learn
svclassifier = SVC(kernel='linear')          # Use linear kernel and separate the data
svclassifier.fit(X_train, y_train)

SVC(kernel='linear')

In [9]:
#To make predictions
y_pred = svclassifier.predict(X_test)

Evaluating the Algorithm

Confusion matrix, precision, recall, and F1 measures are the most commonly used metrics for classification tasks. Scikit-Learn's metrics library contains the classification_report and confusion_matrix methods, which can be readily used to find out the values for these important metrics.

In [10]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))                                  # Displays confusion matrix and classification report
print(classification_report(y_test,y_pred))

[[196   3]
 [  0 144]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       199
           1       0.98      1.00      0.99       144

    accuracy                           0.99       343
   macro avg       0.99      0.99      0.99       343
weighted avg       0.99      0.99      0.99       343

In [11]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
# Read dataset to pandas dataframe
irisdata = pd.read_csv(url, names=colnames)

In [13]:
irisdata

     sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [14]:
X = irisdata.drop('Class', axis=1)
y = irisdata['Class']

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)        # 75% training and 25% testing
X_train

     sepal-length  sepal-width  petal-length  petal-width
131           7.9          3.8           6.4          2.0
102           7.1          3.0           5.9          2.1
39            5.1          3.4           1.5          0.2
99            5.7          2.8           4.1          1.3
33            5.5          4.2           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
75            6.6          3.0           4.4          1.4
69            5.6          2.5           3.9          1.1
112           6.8          3.0           5.5          2.1
107           7.3          2.9           6.3          1.8

[112 rows x 4 columns]

from matplotlib import pyplot as plt
X_train['sepal-length'].plot(kind='hist', bins=20, title='sepal-length')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_train['sepal-width'].plot(kind='hist', bins=20, title='sepal-width')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_train['petal-length'].plot(kind='hist', bins=20, title='petal-length')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_train['petal-width'].plot(kind='hist', bins=20, title='petal-width')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_train.plot(kind='scatter', x='sepal-length', y='sepal-width', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_train.plot(kind='scatter', x='sepal-width', y='petal-length', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_train.plot(kind='scatter', x='petal-length', y='petal-width', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
X_train['sepal-length'].plot(kind='line', figsize=(8, 4), title='sepal-length')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
X_train['sepal-width'].plot(kind='line', figsize=(8, 4), title='sepal-width')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
X_train['petal-length'].plot(kind='line', figsize=(8, 4), title='petal-length')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
X_train['petal-width'].plot(kind='line', figsize=(8, 4), title='petal-width')
plt.gca().spines[['top', 'right']].set_visible(False)

In [16]:
from sklearn.svm import SVC
# svclassifier = SVC(kernel='poly', degree=8)
svclassifier = SVC(kernel='rbf') #Gaussian Kernel
# svclassifier = SVC(kernel='sigmoid') #Sigmoid Kernel
svclassifier.fit(X_train, y_train)

SVC()

In [17]:
y_pred = svclassifier.predict(X_test)

In [18]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))                                  # Displays confusion matrix and classification report
print(classification_report(y_test, y_pred))

[[12  0  0]
 [ 0 11  0]
 [ 0  2 13]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.85      1.00      0.92        11
 Iris-virginica       1.00      0.87      0.93        15

       accuracy                           0.95        38
      macro avg       0.95      0.96      0.95        38
   weighted avg       0.96      0.95      0.95        38